remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/KatherineWhan/doco-test"

# Add this to enable emojis
plugins: - jemoji

